// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4ulMdMjLKBRutvv0S6S37tQiaM2Gre74',
    appId: '1:838048382384:web:d6d315098eb919b4ef6a75',
    messagingSenderId: '838048382384',
    projectId: 'fishtankproject-f0a11',
    authDomain: 'fishtankproject-f0a11.firebaseapp.com',
    storageBucket: 'fishtankproject-f0a11.firebasestorage.app',
    measurementId: 'G-J8D7M2FEY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZy-3vJo5bLoSigeJqkgO7JS_9XdXjITg',
    appId: '1:838048382384:android:2cf40cc4e7ab8533ef6a75',
    messagingSenderId: '838048382384',
    projectId: 'fishtankproject-f0a11',
    storageBucket: 'fishtankproject-f0a11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Hx6Oi43QRr3VnOFEjMjjoWefcY_iRcM',
    appId: '1:838048382384:ios:d7d45a0988780809ef6a75',
    messagingSenderId: '838048382384',
    projectId: 'fishtankproject-f0a11',
    storageBucket: 'fishtankproject-f0a11.firebasestorage.app',
    iosBundleId: 'com.iotbigdata.fishtank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8Hx6Oi43QRr3VnOFEjMjjoWefcY_iRcM',
    appId: '1:838048382384:ios:2f99cd75da046d37ef6a75',
    messagingSenderId: '838048382384',
    projectId: 'fishtankproject-f0a11',
    storageBucket: 'fishtankproject-f0a11.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4ulMdMjLKBRutvv0S6S37tQiaM2Gre74',
    appId: '1:838048382384:web:73021588452d9e44ef6a75',
    messagingSenderId: '838048382384',
    projectId: 'fishtankproject-f0a11',
    authDomain: 'fishtankproject-f0a11.firebaseapp.com',
    storageBucket: 'fishtankproject-f0a11.firebasestorage.app',
    measurementId: 'G-C7LWYGB1W0',
  );
}
